### ISSUE TITLE
Error when accessing tasks

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9552]
**Describe the bug**
When loading tasks or targets for the first time after the upgrade to 4.13, this error can occur. 
![Image](https://github.com/user-attachments/assets/6e1faf66-5271-45f0-b693-29237b922a5e)

**To Reproduce**
1. Install 4.12
2. Create an offline user. Log in with this offline user and create one pregnancy. Logout. 
4. Login as admin and upgrade to 4.13.x . Logout. 
5. Log in as the offline user again and navigate to tasks or targets page. 
6. See error. 

**Expected behavior**
No error. 

**Logs**
```
main.js:1 Error getting targets TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.aggregateStoredTargetEmissions (main.js:1:1309050)
    at Object.<anonymous> (main.js:1:1306901)
    at Generator.next (<anonymous>)
    at w (main.js:11:600733)
    at x (main.js:11:600945)
    at main.js:11:601004
    at new r (polyfills.js:1:22887)
    at Object.<anonymous> (main.js:11:600886)
    at A.aggregateStoredTargetEmissions (main.js:1:1307030)
```

**Screenshots**

**Environment**
- App: webapp
- Version: 4.13

**Additional context**
This is due to a change in structure of the local rulesStateStore document.

**Comment by dianabarsan** [comment]
Fixed in master and backported to 4.13.x

**Comment by kennsippell** [comment]
Reactivating due to similar bug:

1. Install 4.12
1. Create an offline user. Log in with this offline user and create one pregnancy. Logout.
1. Login as admin and upgrade to 4.13.x . Logout.
1. **Move calendar forward to start of next month**
1. Log in as the offline user again and navigate to tasks or targets page.
1. See error.

**Comment by kennsippell** [comment]
Yes

**Comment by garethbowen** [comment]
Second patch has been merged and backported.
